server:
  port: 8080

spring:
  application:
    name: shoppingmall
  datasource:
    url: jdbc:mariadb://localhost:13306/shoppingmall
    username: shoppingmall_api
    password: a3Bq7kLp
    driver-class-name: org.mariadb.jdbc.Driver
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  configuration:
    map-underscore-to-camel-case: true