version: '3.8'

services:
  db:
    image: mariadb:11.4
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: shoppingmall
      MYSQL_USER: shoppingmall_api
      MYSQL_PASSWORD: a3Bq7kLp
    ports:
      - "13306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: